version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL_PG=postgresql://appuser:apppassword@postgres:5432/materials_db
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET=mrs
      - S3_ACCESS_KEY=minio_user
      - S3_SECRET_KEY=minio_password
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000

  faiss:
    image: python:3.11-slim
    container_name: faiss_indexer
    volumes:
      - ./data/embeddings:/app/embeddings
    working_dir: /app
    command: tail -f /dev/null
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: materials_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - ./data/minio_data:/data

volumes:
  postgres_data:
  minio_data: